// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.36/04       [402436]
Creator        : nick
Date           : Wed Feb 25 12:26:37 2026
Host           : Linux e3a25599b92e 4.18.0-553.50.1.el8_10.x86_64 #1 SMP Tue Apr 15 08:09:22 EDT 2025 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/nick/ggHAnalysis
Training events: 3862
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "150" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
m_2b                          m_2b                          m_2b                          m_2b                                                            'F'    [75.0588531494,174.993347168]
pt_2b                         pt_2b                         pt_2b                         pt_2b                                                           'F'    [3.95076417923,1489.56030273]
met                           met                           met                           met                                                             'F'    [0.978554308414,139.972229004]
ht                            ht                            ht                            ht                                                              'F'    [849.839050293,5693.98095703]
dphi_j1j2                     dphi_j1j2                     dphi_j1j2                     dphi_j1j2                                                       'F'    [3.00004339218,3.14158391953]
dR_j1j2                       dR_j1j2                       dR_j1j2                       dR_j1j2                                                         'F'    [3.00153517723,5.56691074371]
abs_dm_j1j2                   abs_dm_j1j2                   abs_dm_j1j2                   abs_dm_j1j2                                                     'F'    [0.0273933410645,439.011535645]
dphi_met_bb                   dphi_met_bb                   dphi_met_bb                   dphi_met_bb                                                     'F'    [0.000264763832092,3.14146924019]
dphi_met_j1                   dphi_met_j1                   dphi_met_j1                   dphi_met_j1                                                     'F'    [0.000268667936325,3.14147162437]
min_dphi_met_jet              min_dphi_met_jet              min_dphi_met_jet              min_dphi_met_jet                                                'F'    [8.15391540527e-05,1.55469822884]
pt_j1                         pt_j1                         pt_j1                         pt_j1                                                           'F'    [450.053863525,2825.34228516]
pt_j2                         pt_j2                         pt_j2                         pt_j2                                                           'F'    [350.022491455,2559.0715332]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDTNode

#ifndef BDTNode__def
#define BDTNode__def

class BDTNode {

public:

   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 12 )
   {
      // the training input variables
      const char* inputVars[] = { "m_2b", "pt_2b", "met", "ht", "dphi_j1j2", "dR_j1j2", "abs_dm_j1j2", "dphi_met_bb", "dphi_met_j1", "min_dphi_met_jet", "pt_j1", "pt_j2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.19662,-0.0606761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667991,0.0335981) , 
0, 103.598, 1, 0, 0.570676,0.0706764) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0365953,-0.0926809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350301,-0.0299399) , 
7, 2.0936, 1, 0, 0.144233,-0.355767) , 
0, 141.682, 1, 0, 0.5,-1.02764e-14)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.211895,-0.0520841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.635532,0.0247024) , 
0, 104.064, 1, 0, 0.551703,0.0475766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0204675,-0.0888688) , 
0, 151.199, 1, 0, 0.5,-1.68716e-05)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.241477,-0.0435283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.678779,0.0300343) , 
0, 106.769, 1, 0, 0.570676,0.0594545) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0365953,-0.0803384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350301,-0.0245505) , 
7, 2.0936, 1, 0, 0.144233,-0.299677) , 
0, 141.682, 1, 0, 0.5,-6.58834e-05)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.118827,-0.0622274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.644638,0.0225906) , 
0, 97.2563, 1, 0, 0.570676,0.0535089) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0365953,-0.0745341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350301,-0.0221722) , 
7, 2.0936, 1, 0, 0.144233,-0.270058) , 
0, 141.682, 1, 0, 0.5,-0.000117299)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.211895,-0.0407257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.635532,0.0189729) , 
0, 104.064, 1, 0, 0.551703,0.0362406) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0204675,-0.0739075) , 
0, 151.199, 1, 0, 0.5,-0.000200556)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.118827,-0.0543726) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.644638,0.0191147) , 
0, 97.2563, 1, 0, 0.570676,0.0449457) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343687,-0.0160002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0526204,-0.0662433) , 
8, 1.19691, 1, 0, 0.144233,-0.227869) , 
0, 141.682, 1, 0, 0.5,-0.000269105)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.264376,-0.0302918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.643471,0.0174681) , 
0, 107.689, 1, 0, 0.551703,0.0300876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0204675,-0.067384) , 
0, 151.199, 1, 0, 0.5,-0.000341696)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.258902,-0.0282923) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.693064,0.0227597) , 
0, 107.455, 1, 0, 0.574277,0.0443995) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0581066,-0.0699388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304284,-0.0225827) , 
9, 0.145599, 1, 0, 0.224887,-0.166271) , 
0, 136.923, 1, 0, 0.5,-0.000386941)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.149041,-0.0405577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640265,0.0225197) , 
0, 98.8632, 1, 0, 0.574585,0.0686552) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.265224,-0.044666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45639,-0.00998698) , 
1, 499.154, 1, 0, 0.388228,-0.103851) , 
6, 20.9314, 1, 0, 0.5,-0.000385865)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.118827,-0.0440521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.644638,0.0147815) , 
0, 97.2563, 1, 0, 0.570676,0.0349644) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0455349,-0.063646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.254606,-0.0192125) , 
1, 572.411, 1, 0, 0.144233,-0.178196) , 
0, 141.682, 1, 0, 0.5,-0.000363555)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375418,-0.0204773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.643317,0.0246451) , 
1, 465.581, 1, 0, 0.574585,0.0614745) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473678,-0.0112633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.122672,-0.0522857) , 
0, 136.872, 1, 0, 0.388228,-0.0931559) , 
6, 20.9314, 1, 0, 0.5,-0.000412434)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0887442,-0.0482908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60284,0.0099408) , 
0, 93.1869, 1, 0, 0.551703,0.0229565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0204675,-0.0605197) , 
0, 151.199, 1, 0, 0.5,-0.000393835)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375418,-0.0181978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.643317,0.0222498) , 
1, 465.581, 1, 0, 0.574585,0.0551627) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.265224,-0.039289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45639,-0.0072001) , 
1, 499.154, 1, 0, 0.388228,-0.0837993) , 
6, 20.9314, 1, 0, 0.5,-0.000453333)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318969,-0.0177057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701807,0.0190505) , 
0, 110.4, 1, 0, 0.574277,0.0340768) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0581066,-0.063204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304284,-0.0175431) , 
9, 0.145599, 1, 0, 0.224887,-0.128133) , 
0, 136.923, 1, 0, 0.5,-0.000407475)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343799,-0.0174686) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.124909,-0.059095) , 
5, 3.20559, 1, 0, 0.229095,-0.165097) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57149,0.0103567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.242119,-0.0442935) , 
6, 41.6868, 1, 0, 0.537549,0.022435) , 
1, 428.411, 1, 0, 0.5,-0.000393876)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0887442,-0.0435747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60284,0.00843348) , 
0, 93.1869, 1, 0, 0.551703,0.0192309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0204675,-0.0571584) , 
0, 151.199, 1, 0, 0.5,-0.000379718)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375418,-0.0148974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.643317,0.0191756) , 
1, 465.581, 1, 0, 0.574585,0.0473272) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.265224,-0.0347194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45639,-0.00642782) , 
1, 499.154, 1, 0, 0.388228,-0.0719951) , 
6, 20.9314, 1, 0, 0.5,-0.000428532)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318969,-0.0147231) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701807,0.0161793) , 
0, 110.4, 1, 0, 0.574277,0.0290877) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40535,-0.00114165) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.147355,-0.0418216) , 
8, 1.04733, 1, 0, 0.224887,-0.109551) , 
0, 136.923, 1, 0, 0.5,-0.000385476)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.149041,-0.0286785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640265,0.0147736) , 
0, 98.8632, 1, 0, 0.574585,0.0425479) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.265224,-0.0314637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45639,-0.00599454) , 
1, 499.154, 1, 0, 0.388228,-0.0646783) , 
6, 20.9314, 1, 0, 0.5,-0.000366674)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.258902,-0.01579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.693064,0.0132458) , 
0, 107.455, 1, 0, 0.574277,0.0266346) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0581066,-0.0579892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304284,-0.013442) , 
9, 0.145599, 1, 0, 0.224887,-0.100259) , 
0, 136.923, 1, 0, 0.5,-0.000341683)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490735,-0.0047827) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670611,0.019169) , 
1, 552.276, 1, 0, 0.551703,0.0156424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0204675,-0.0538905) , 
0, 151.199, 1, 0, 0.5,-0.000336747)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375418,-0.0131974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.643317,0.016356) , 
1, 465.581, 1, 0, 0.574585,0.0383509) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439691,-0.00628397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.252908,-0.034682) , 
6, 40.8403, 1, 0, 0.388228,-0.0583299) , 
6, 20.9314, 1, 0, 0.5,-0.000343162)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0913826,-0.0365606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.63441,0.00900078) , 
0, 92.7296, 1, 0, 0.574277,0.0228143) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.152673,-0.0399226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313999,-0.00473207) , 
1, 572.411, 1, 0, 0.224887,-0.0859485) , 
0, 136.923, 1, 0, 0.5,-0.000307631)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343799,-0.00973107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.124909,-0.0503783) , 
5, 3.20559, 1, 0, 0.229095,-0.1157) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57149,0.0079032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.242119,-0.0361003) , 
6, 41.6868, 1, 0, 0.537549,0.0156784) , 
1, 428.411, 1, 0, 0.5,-0.00031471)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.21877,-0.0175529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6575,0.00865131) , 
0, 105.647, 1, 0, 0.561057,0.0158159) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.0634649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193178,-0.0130979) , 
1, 572.411, 1, 0, 0.0918495,-0.108063) , 
0, 146.441, 1, 0, 0.5,-0.000304227)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539371,0.00237202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.710598,0.0294123) , 
1, 597.105, 1, 0, 0.574585,0.0333669) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505913,0.00575768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343483,-0.0194846) , 
8, 1.19692, 1, 0, 0.388228,-0.0508082) , 
6, 20.9314, 1, 0, 0.5,-0.000322059)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490735,-0.00394061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670611,0.0157613) , 
1, 552.276, 1, 0, 0.551703,0.0124284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0204675,-0.0507612) , 
0, 151.199, 1, 0, 0.5,-0.0002838)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617555,0.0159067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513707,-0.00501563) , 
6, 10.9745, 1, 0, 0.574585,0.0301947) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410519,-0.0066132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274116,-0.0347054) , 
5, 3.52213, 1, 0, 0.388228,-0.0459694) , 
6, 20.9314, 1, 0, 0.5,-0.000288045)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343799,-0.007885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.124909,-0.0459123) , 
5, 3.20559, 1, 0, 0.229095,-0.0981662) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64264,0.0217708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500399,-0.00355595) , 
11, 401.378, 1, 0, 0.537549,0.0133146) , 
1, 428.411, 1, 0, 0.5,-0.000256287)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598989,0.00839183) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408826,-0.0238721) , 
5, 3.61234, 1, 0, 0.574277,0.0184615) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0581066,-0.0530654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304284,-0.00827927) , 
9, 0.145599, 1, 0, 0.224887,-0.069501) , 
0, 136.923, 1, 0, 0.5,-0.000238502)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407461,-0.0103121) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.624626,0.00866523) , 
1, 483.735, 1, 0, 0.551703,0.0106666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0204675,-0.0486162) , 
0, 151.199, 1, 0, 0.5,-0.00023558)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.149041,-0.0225726) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640265,0.010363) , 
0, 98.8632, 1, 0, 0.574585,0.026997) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505913,0.00594583) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343483,-0.0165822) , 
8, 1.19692, 1, 0, 0.388228,-0.0410648) , 
6, 20.9314, 1, 0, 0.5,-0.00024304)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598989,0.00746226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408826,-0.021586) , 
5, 3.61234, 1, 0, 0.574277,0.0160028) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.15409,-0.0305681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416034,0.00651188) , 
7, 2.39265, 1, 0, 0.224887,-0.0603209) , 
0, 136.923, 1, 0, 0.5,-0.000222897)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343799,-0.00663368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.124909,-0.0414271) , 
5, 3.20559, 1, 0, 0.229095,-0.0830572) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57149,0.00623662) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.242119,-0.0307016) , 
6, 41.6868, 1, 0, 0.537549,0.0112703) , 
1, 428.411, 1, 0, 0.5,-0.000212493)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501453,0.00240454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321174,-0.0302416) , 
11, 455.215, 1, 0, 0.46102,-0.0196729) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657806,0.0242054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486421,-0.00852335) , 
11, 555.764, 1, 0, 0.587312,0.0433962) , 
1, 569.897, 1, 0, 0.5,-0.000206477)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0362194,-0.0498021) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608397,0.00554687) , 
0, 87.7431, 1, 0, 0.570676,0.0127588) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0365953,-0.0477917) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350301,0.00532414) , 
7, 2.0936, 1, 0, 0.144233,-0.0653125) , 
0, 141.682, 1, 0, 0.5,-0.000180283)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539371,0.00090351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.710598,0.0246538) , 
1, 597.105, 1, 0, 0.574585,0.0229813) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358954,-0.0131698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.533168,0.0118728) , 
4, 3.12812, 1, 0, 0.388228,-0.0349883) , 
6, 20.9314, 1, 0, 0.5,-0.000219606)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490735,-0.00332967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670611,0.0124355) , 
1, 552.276, 1, 0, 0.551703,0.00876344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0204675,-0.0463021) , 
0, 151.199, 1, 0, 0.5,-0.000191534)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598989,0.00648741) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219427,-0.0173006) , 
0, 136.923, 1, 0, 0.519469,0.0102405) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.207021,-0.0411615) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500556,0.000331409) , 
0, 117.964, 1, 0, 0.373467,-0.0680178) , 
5, 3.61234, 1, 0, 0.5,-0.000195042)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564946,0.0147757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25577,-0.0300942) , 
0, 132.125, 1, 0, 0.512248,0.0340569) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272461,-0.0340064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550646,0.0020924) , 
1, 499.154, 1, 0, 0.492943,-0.0199135) , 
3, 1080.51, 1, 0, 0.5,-0.000184755)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618797,0.0192842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551996,-0.00184139) , 
11, 397.394, 1, 0, 0.574585,0.0210586) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374056,-0.0116992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478958,0.0153457) , 
2, 93.641, 1, 0, 0.388228,-0.0319862) , 
6, 20.9314, 1, 0, 0.5,-0.000171261)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.151839,-0.0059677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.287635,-0.0282249) , 
0, 103.596, 1, 0, 0.229095,-0.0696737) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64264,0.0186179) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500399,-0.00349769) , 
11, 401.378, 1, 0, 0.537549,0.00948625) , 
1, 428.411, 1, 0, 0.5,-0.000150131)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.192999,-0.02985) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417439,0.0245728) , 
2, 73.4657, 1, 0, 0.263959,-0.0468251) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713587,0.0124452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410484,-0.00875275) , 
0, 127.435, 1, 0, 0.56908,0.0135354) , 
0, 108.37, 1, 0, 0.5,-0.000130342)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520654,0.00306422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308101,-0.0262892) , 
0, 127.405, 1, 0, 0.46102,-0.0162721) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657806,0.0218185) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486421,-0.00860163) , 
11, 555.764, 1, 0, 0.587312,0.0360281) , 
1, 569.897, 1, 0, 0.5,-0.000129572)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540958,0.0116566) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507095,-0.00313557) , 
3, 1080.51, 1, 0, 0.519469,0.0092294) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.207021,-0.0377939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500556,0.000362646) , 
0, 117.964, 1, 0, 0.373467,-0.0608111) , 
5, 3.61234, 1, 0, 0.5,-0.000110306)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343799,-0.00411867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.124909,-0.0352964) , 
5, 3.20559, 1, 0, 0.229095,-0.0626789) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587278,0.00688834) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357039,-0.0153439) , 
6, 31.2719, 1, 0, 0.537549,0.0085692) , 
1, 428.411, 1, 0, 0.5,-0.000104053)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.192999,-0.0277039) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417439,0.0222796) , 
2, 73.4657, 1, 0, 0.263959,-0.0423248) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624041,0.0112674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487211,-0.00947351) , 
2, 47.3098, 1, 0, 0.56908,0.0122561) , 
0, 108.37, 1, 0, 0.5,-0.000101153)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407461,-0.00879407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.624626,0.00685101) , 
1, 483.735, 1, 0, 0.551703,0.00734093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0204675,-0.0438773) , 
0, 151.199, 1, 0, 0.5,-0.000102178)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623527,0.0205504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26329,-0.0212039) , 
0, 127.384, 1, 0, 0.526546,0.0446414) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523616,0.00717959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472802,-0.0100079) , 
3, 1094.94, 1, 0, 0.493499,-0.0110727) , 
7, 0.149846, 1, 0, 0.5,-0.000112283)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501453,0.00209671) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321174,-0.0251754) , 
11, 455.215, 1, 0, 0.46102,-0.0153862) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697911,0.0286361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529787,-0.000844934) , 
11, 504.427, 1, 0, 0.587312,0.034151) , 
1, 569.897, 1, 0, 0.5,-9.6483e-05)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593771,0.0047579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.140285,-0.0195896) , 
0, 141.682, 1, 0, 0.519469,0.00845543) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.207021,-0.034674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500556,-0.000386586) , 
0, 117.964, 1, 0, 0.373467,-0.0555639) , 
5, 3.61234, 1, 0, 0.5,-8.13674e-05)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471953,0.00156818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178138,-0.0466887) , 
0, 127.405, 1, 0, 0.407216,-0.0262471) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608729,0.00895064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.226409,-0.0314632) , 
6, 41.6868, 1, 0, 0.563424,0.0178014) , 
1, 499.154, 1, 0, 0.5,-8.32554e-05)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322851,0.00260321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0999201,-0.0487399) , 
7, 1.19561, 1, 0, 0.263959,-0.0386886) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624041,0.0103934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487211,-0.0086308) , 
2, 47.3098, 1, 0, 0.56908,0.0112165) , 
0, 108.37, 1, 0, 0.5,-8.21002e-05)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431149,-0.0213496) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.602828,0.0137505) , 
9, 0.815352, 1, 0, 0.484393,-0.0382908) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569493,0.0110276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449327,-0.00396015) , 
2, 48.8893, 1, 0, 0.504779,0.0116101) , 
2, 27.4535, 1, 0, 0.5,-8.71134e-05)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304058,-0.0156337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.607349,0.0204216) , 
1, 464.718, 1, 0, 0.526546,0.0413992) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519686,0.000373276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313064,-0.0255331) , 
5, 3.61234, 1, 0, 0.493499,-0.0102287) , 
7, 0.149846, 1, 0, 0.5,-7.2138e-05)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546952,0.0143756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397895,-0.0178523) , 
11, 428.762, 1, 0, 0.512248,0.0258476) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272461,-0.0283458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550646,0.00193268) , 
1, 499.154, 1, 0, 0.492943,-0.0149924) , 
3, 1080.51, 1, 0, 0.5,-6.34102e-05)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.66185,0.0214006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548395,-0.000983408) , 
6, 4.00815, 1, 0, 0.574585,0.0157293) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.283624,-0.0286599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407848,-0.00211698) , 
4, 3.04061, 1, 0, 0.388228,-0.0237198) , 
6, 20.9314, 1, 0, 0.5,-5.91902e-05)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407461,-0.0078289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.624626,0.00604204) , 
1, 483.735, 1, 0, 0.551703,0.0062454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0204675,-0.0416873) , 
0, 151.199, 1, 0, 0.5,-4.93371e-05)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431149,-0.0192021) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.602828,0.0120418) , 
9, 0.815352, 1, 0, 0.484393,-0.0348077) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586501,0.0118932) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45805,-0.00253778) , 
2, 43.5315, 1, 0, 0.504779,0.0105775) , 
2, 27.4535, 1, 0, 0.5,-6.11779e-05)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623527,0.0181161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26329,-0.0195177) , 
0, 127.384, 1, 0, 0.526546,0.0381162) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523616,0.00666864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472802,-0.00902797) , 
3, 1094.94, 1, 0, 0.493499,-0.00939663) , 
7, 0.149846, 1, 0, 0.5,-4.95961e-05)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501453,0.00201697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321174,-0.0226978) , 
11, 455.215, 1, 0, 0.46102,-0.0131695) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657806,0.0186777) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486421,-0.00718164) , 
11, 555.764, 1, 0, 0.587312,0.0293661) , 
1, 569.897, 1, 0, 0.5,-4.07857e-05)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593771,0.00407704) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.140285,-0.0175148) , 
0, 141.682, 1, 0, 0.519469,0.00711193) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.207021,-0.0311333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500556,0.000383504) , 
0, 117.964, 1, 0, 0.373467,-0.0464695) , 
5, 3.61234, 1, 0, 0.5,-3.30125e-05)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376922,-0.00841157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569972,0.00656565) , 
1, 483.735, 1, 0, 0.503528,0.00581906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466015,-0.0148737) , 
7, 2.84231, 1, 0, 0.5,-3.76493e-05)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0885649,-0.0257582) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564379,0.00917754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507304,-0.00420985) , 
3, 1094.94, 1, 0, 0.529771,0.00471218) , 
0, 89.3352, 1, 0, 0.5,-3.177e-05)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520654,0.00281954) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308101,-0.0222489) , 
0, 127.405, 1, 0, 0.46102,-0.0122512) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648424,0.0170629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488818,-0.00822451) , 
2, 47.3227, 1, 0, 0.587312,0.027331) , 
1, 569.897, 1, 0, 0.5,-3.40754e-05)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.260382,-0.0339766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563549,-0.000915389) , 
0, 113.225, 1, 0, 0.484393,-0.0332458) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586501,0.0106262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45805,-0.00190729) , 
2, 43.5315, 1, 0, 0.504779,0.0101451) , 
2, 27.4535, 1, 0, 0.5,-2.61137e-05)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60875,0.0098918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501314,-0.00909839) , 
6, 12.9648, 1, 0, 0.574585,0.0144259) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364666,-0.00987567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494797,0.0133922) , 
1, 640.641, 1, 0, 0.388228,-0.0216813) , 
6, 20.9314, 1, 0, 0.5,-2.50641e-05)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304058,-0.0145544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.607349,0.0182699) , 
1, 464.718, 1, 0, 0.526546,0.035149) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526699,0.00327854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438982,-0.0119225) , 
10, 563.163, 1, 0, 0.493499,-0.00863192) , 
7, 0.149846, 1, 0, 0.5,-1.90512e-05)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540958,0.00868528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507095,-0.00234954) , 
3, 1080.51, 1, 0, 0.519469,0.00657361) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.207021,-0.0288854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500556,-2.44441e-05) , 
0, 117.964, 1, 0, 0.373467,-0.0428231) , 
5, 3.61234, 1, 0, 0.5,-1.33091e-05)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520654,0.00251662) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308101,-0.0205356) , 
0, 127.405, 1, 0, 0.46102,-0.0115195) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697911,0.0249758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529787,-0.00170112) , 
11, 504.427, 1, 0, 0.587312,0.025754) , 
1, 569.897, 1, 0, 0.5,-1.49401e-05)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.192999,-0.0242278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417439,0.0214159) , 
2, 73.4657, 1, 0, 0.263959,-0.0314114) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609234,0.00510351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251999,-0.0202483) , 
6, 41.8354, 1, 0, 0.56908,0.00918274) , 
0, 108.37, 1, 0, 0.5,-7.87241e-06)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417654,-0.0225748) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595277,0.0148763) , 
8, 0.226932, 1, 0, 0.558479,0.0283544) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49733,0.00199435) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388623,-0.0269241) , 
7, 1.49608, 1, 0, 0.480168,-0.00964407) , 
8, 1.19692, 1, 0, 0.5,-2.09997e-05)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456114,0.00327987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293567,-0.0299756) , 
0, 122.647, 1, 0, 0.407216,-0.0203059) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608729,0.00734466) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.226409,-0.0263428) , 
6, 41.6868, 1, 0, 0.563424,0.0138573) , 
1, 499.154, 1, 0, 0.5,-1.36971e-05)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431149,-0.0169936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.602828,0.011087) , 
9, 0.815352, 1, 0, 0.484393,-0.0296971) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569493,0.00878352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449327,-0.00302633) , 
2, 48.8893, 1, 0, 0.504779,0.00907632) , 
2, 27.4535, 1, 0, 0.5,-1.24956e-05)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0690107,-0.0496231) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51955,0.000638458) , 
1, 398.021, 1, 0, 0.489407,-0.00640222) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484818,-0.00596819) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.662557,0.0279057) , 
7, 2.09446, 1, 0, 0.566673,0.0402426) , 
1, 640.641, 1, 0, 0.5,-7.34665e-06)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524793,-0.0011512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.694067,0.0139391) , 
1, 620.817, 1, 0, 0.551703,0.00523304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0204675,-0.0393866) , 
0, 151.199, 1, 0, 0.5,-1.80603e-05)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423883,-0.0209786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500932,0.000264717) , 
8, 0.299431, 1, 0, 0.495474,-0.00442821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558977,0.0148536) , 
4, 3.13484, 1, 0, 0.5,-2.79311e-05)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4497,-0.0130064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.64931,0.0303007) , 
8, 0.312652, 1, 0, 0.55042,0.0368776) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243464,-0.0147713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565546,0.00189936) , 
0, 108.37, 1, 0, 0.490962,-0.00663791) , 
8, 0.598593, 1, 0, 0.5,-2.34324e-05)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556428,0.0171191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449294,-0.0100998) , 
11, 405.14, 1, 0, 0.512248,0.0212478) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475494,-0.0081745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554513,0.0137839) , 
8, 2.99189, 1, 0, 0.492943,-0.012277) , 
3, 1080.51, 1, 0, 0.5,-2.20674e-05)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540958,0.00828335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507095,-0.00233725) , 
3, 1080.51, 1, 0, 0.519469,0.00598357) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445687,0.00141371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300441,-0.0249236) , 
2, 41.5392, 1, 0, 0.373467,-0.0390008) , 
5, 3.61234, 1, 0, 0.5,-1.49767e-05)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343848,-0.023938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.55875,0.00104386) , 
0, 117.962, 1, 0, 0.484393,-0.0272502) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523032,0.0054093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446615,-0.00834809) , 
3, 1311.19, 1, 0, 0.504779,0.00832573) , 
2, 27.4535, 1, 0, 0.5,-1.35766e-05)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474604,0.000737931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0850792,-0.0513136) , 
0, 132.164, 1, 0, 0.407216,-0.0183295) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661532,0.0170535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510642,-0.00392687) , 
11, 452.733, 1, 0, 0.563424,0.0125098) , 
1, 499.154, 1, 0, 0.5,-1.16183e-05)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477379,0.00275507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422819,-0.015501) , 
7, 1.19623, 1, 0, 0.46102,-0.0101058) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648424,0.0150998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488818,-0.00780774) , 
2, 47.3227, 1, 0, 0.587312,0.0225795) , 
1, 569.897, 1, 0, 0.5,-1.74019e-05)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4497,-0.0112205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.64931,0.0281452) , 
8, 0.312652, 1, 0, 0.55042,0.0354867) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243464,-0.013874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565546,0.00170195) , 
0, 108.37, 1, 0, 0.490962,-0.00637303) , 
8, 0.598593, 1, 0, 0.5,-1.02307e-05)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575504,0.00312226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371605,-0.00763179) , 
6, 20.9314, 1, 0, 0.495474,-0.00414863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558977,0.0140818) , 
4, 3.13484, 1, 0, 0.5,-9.95467e-06)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232046,-0.048857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.581039,0.00866667) , 
1, 485.272, 1, 0, 0.464585,-0.0339969) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545766,0.0123142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489449,-0.00299376) , 
4, 3.06974, 1, 0, 0.506465,0.00619579) , 
4, 3.03374, 1, 0, 0.5,-8.34587e-06)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623527,0.015215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26329,-0.0178092) , 
0, 127.384, 1, 0, 0.526546,0.0295952) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523616,0.00592808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472802,-0.00768307) , 
3, 1094.94, 1, 0, 0.493499,-0.00725615) , 
7, 0.149846, 1, 0, 0.5,-6.49771e-06)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0690107,-0.0457371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51955,0.000469566) , 
1, 398.021, 1, 0, 0.489407,-0.00569999) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643598,0.0272197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497324,-0.00551932) , 
11, 607.1, 1, 0, 0.566673,0.0358546) , 
1, 640.641, 1, 0, 0.5,-2.9722e-06)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431149,-0.0154445) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.602828,0.0105647) , 
9, 0.815352, 1, 0, 0.484393,-0.0258556) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525201,0.00492622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424285,-0.00929969) , 
5, 3.49018, 1, 0, 0.504779,0.00790149) , 
2, 27.4535, 1, 0, 0.5,-1.14639e-05)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524793,-0.00107111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.694067,0.0127194) , 
1, 620.817, 1, 0, 0.551703,0.00465398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0204675,-0.037843) , 
0, 151.199, 1, 0, 0.5,-7.53815e-06)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587551,0.0120328) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278249,-0.0212779) , 
0, 127.384, 1, 0, 0.498654,0.0161536) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554618,0.00462285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34729,-0.0262906) , 
2, 47.0363, 1, 0, 0.500989,-0.0118934) , 
7, 0.449008, 1, 0, 0.5,-1.68585e-05)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4497,-0.0102139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.64931,0.0264553) , 
8, 0.312652, 1, 0, 0.55042,0.0336435) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243464,-0.013311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565546,0.00162987) , 
0, 108.37, 1, 0, 0.490962,-0.00604629) , 
8, 0.598593, 1, 0, 0.5,-1.33212e-05)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528942,0.00462862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437255,-0.0201072) , 
11, 441.312, 1, 0, 0.484393,-0.0254009) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556263,0.00890495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473373,-0.00216615) , 
8, 2.39357, 1, 0, 0.504779,0.00776079) , 
2, 27.4535, 1, 0, 0.5,-1.25839e-05)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575504,0.00287965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371605,-0.00710875) , 
6, 20.9314, 1, 0, 0.495474,-0.00388236) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558977,0.0133391) , 
4, 3.13484, 1, 0, 0.5,-8.00394e-06)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587551,0.0114076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278249,-0.019197) , 
0, 127.384, 1, 0, 0.498654,0.0159847) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554618,0.0039898) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34729,-0.0243293) , 
2, 47.0363, 1, 0, 0.500989,-0.0117516) , 
7, 0.449008, 1, 0, 0.5,-6.6096e-06)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501453,0.00159271) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321174,-0.0170458) , 
11, 455.215, 1, 0, 0.46102,-0.00914285) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697911,0.0226144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529787,-0.00221329) , 
11, 504.427, 1, 0, 0.587312,0.0204643) , 
1, 569.897, 1, 0, 0.5,-4.56907e-06)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232046,-0.0452161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.581039,0.0075553) , 
1, 485.272, 1, 0, 0.464585,-0.0317066) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545766,0.0114365) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489449,-0.00273646) , 
4, 3.06974, 1, 0, 0.506465,0.00578739) , 
4, 3.03374, 1, 0, 0.5,-1.78117e-07)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431149,-0.0145372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.602828,0.00949832) , 
9, 0.815352, 1, 0, 0.484393,-0.0246066) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407253,-0.00413177) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574045,0.00637213) , 
1, 499.154, 1, 0, 0.504779,0.00753446) , 
2, 27.4535, 1, 0, 0.5,3.1746e-07)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593771,0.00333586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.140285,-0.0160711) , 
0, 141.682, 1, 0, 0.519469,0.00533664) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.309971,-0.023034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445107,0.00291978) , 
5, 3.89317, 1, 0, 0.373467,-0.0346607) , 
5, 3.61234, 1, 0, 0.5,3.1081e-06)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0885649,-0.021329) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564379,0.00769873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507304,-0.00368211) , 
3, 1094.94, 1, 0, 0.529771,0.00352688) , 
0, 89.3352, 1, 0, 0.5,-1.14408e-07)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483911,-0.0029687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569138,0.0110975) , 
1, 640.641, 1, 0, 0.495474,-0.00362851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558977,0.012596) , 
4, 3.13484, 1, 0, 0.5,-3.29451e-06)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587551,0.0107511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278249,-0.0175039) , 
0, 127.384, 1, 0, 0.498654,0.0154569) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539743,0.0021668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325188,-0.0278137) , 
2, 53.616, 1, 0, 0.500989,-0.0113545) , 
7, 0.449008, 1, 0, 0.5,-1.21085e-06)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423216,-0.0144329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.61603,0.00907214) , 
1, 577.038, 1, 0, 0.484393,-0.0237522) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556263,0.0084892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473373,-0.00207654) , 
8, 2.39357, 1, 0, 0.504779,0.0072722) , 
2, 27.4535, 1, 0, 0.5,-1.74441e-07)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540958,0.00691873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507095,-0.00193185) , 
3, 1080.51, 1, 0, 0.519469,0.0049316) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328569,-0.024116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418387,0.00233789) , 
4, 3.08774, 1, 0, 0.373467,-0.0320329) , 
5, 3.61234, 1, 0, 0.5,2.47566e-06)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587551,0.00985606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278249,-0.0155753) , 
0, 127.384, 1, 0, 0.498654,0.014527) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554618,0.00322075) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34729,-0.0210473) , 
2, 47.0363, 1, 0, 0.500989,-0.0106646) , 
7, 0.449008, 1, 0, 0.5,2.82668e-06)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39294,-0.0116789) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444699,0.0138298) , 
2, 73.7848, 1, 0, 0.407216,-0.0155577) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661532,0.015518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510642,-0.00369571) , 
11, 452.733, 1, 0, 0.563424,0.0106403) , 
1, 499.154, 1, 0, 0.5,3.34323e-06)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0690107,-0.0416765) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51955,0.00028075) , 
1, 398.021, 1, 0, 0.489407,-0.00510985) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484818,-0.00587185) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.662557,0.02431) , 
7, 2.09446, 1, 0, 0.566673,0.0322182) , 
1, 640.641, 1, 0, 0.5,7.72151e-06)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4497,-0.0109759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.64931,0.0247547) , 
8, 0.312652, 1, 0, 0.55042,0.0288014) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243464,-0.0127133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565546,0.00172185) , 
0, 108.37, 1, 0, 0.490962,-0.0051624) , 
8, 0.598593, 1, 0, 0.5,1.91748e-07)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528942,0.0041888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437255,-0.0181513) , 
11, 441.312, 1, 0, 0.484393,-0.0225822) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523032,0.00466285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446615,-0.00728251) , 
3, 1311.19, 1, 0, 0.504779,0.00691405) , 
2, 27.4535, 1, 0, 0.5,-1.09781e-07)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477379,0.00254422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422819,-0.0138508) , 
7, 1.19623, 1, 0, 0.46102,-0.00847929) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657806,0.0144524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486421,-0.0066369) , 
11, 555.764, 1, 0, 0.587312,0.0190005) , 
1, 569.897, 1, 0, 0.5,2.38439e-06)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366467,-0.00940476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570301,0.00347309) , 
1, 488.96, 1, 0, 0.489407,-0.00497101) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643598,0.0241486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497324,-0.00435116) , 
11, 607.1, 1, 0, 0.566673,0.031338) , 
1, 640.641, 1, 0, 0.5,6.85072e-06)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232046,-0.0400015) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.581039,0.00599989) , 
1, 485.272, 1, 0, 0.464585,-0.0287268) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545766,0.0108631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489449,-0.00266151) , 
4, 3.06974, 1, 0, 0.506465,0.00525461) , 
4, 3.03374, 1, 0, 0.5,9.25587e-06)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575504,0.0026797) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371605,-0.00650706) , 
6, 20.9314, 1, 0, 0.495474,-0.00339488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558977,0.0119536) , 
4, 3.13484, 1, 0, 0.5,8.43717e-06)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404708,-0.00474618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.671092,0.00519702) , 
0, 115.842, 1, 0, 0.561057,0.00464584) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.0597038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193178,0.002567) , 
1, 572.411, 1, 0, 0.0918495,-0.0309938) , 
0, 146.441, 1, 0, 0.5,8.13387e-06)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555572,0.0142741) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445012,-0.0114298) , 
10, 492.94, 1, 0, 0.512248,0.0160743) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475494,-0.00692193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554513,0.0126298) , 
8, 2.99189, 1, 0, 0.492943,-0.00927676) , 
3, 1080.51, 1, 0, 0.5,-9.74096e-06)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488021,0.00158511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398601,-0.0203177) , 
7, 0.449008, 1, 0, 0.462393,-0.015449) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.637426,0.0132846) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462068,-0.00278309) , 
6, 10.4422, 1, 0, 0.521727,0.00891839) , 
9, 0.14814, 1, 0, 0.5,-4.65384e-06)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593771,0.00296153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.140285,-0.0148407) , 
0, 141.682, 1, 0, 0.519469,0.0046121) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.207021,-0.0231884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500556,0.000749643) , 
0, 117.964, 1, 0, 0.373467,-0.0299731) , 
5, 3.61234, 1, 0, 0.5,2.60497e-07)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510524,0.000839955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350305,-0.0174845) , 
3, 1311.19, 1, 0, 0.489407,-0.0046997) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484818,-0.0050555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.662557,0.0223609) , 
7, 2.09446, 1, 0, 0.566673,0.0295515) , 
1, 640.641, 1, 0, 0.5,-3.95784e-06)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528942,0.00396495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437255,-0.0168337) , 
11, 441.312, 1, 0, 0.484393,-0.0206274) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556263,0.00807405) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473373,-0.00217929) , 
8, 2.39357, 1, 0, 0.504779,0.0063145) , 
2, 27.4535, 1, 0, 0.5,-9.07727e-07)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587551,0.00919745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278249,-0.0144986) , 
0, 127.384, 1, 0, 0.498654,0.01347) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522492,0.00083605) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322055,-0.0359699) , 
8, 2.69275, 1, 0, 0.500989,-0.00989044) , 
7, 0.449008, 1, 0, 0.5,1.58102e-06)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366467,-0.00891715) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570301,0.00327981) , 
1, 488.96, 1, 0, 0.489407,-0.0046828) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484818,-0.00382531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.662557,0.021229) , 
7, 2.09446, 1, 0, 0.566673,0.0294924) , 
1, 640.641, 1, 0, 0.5,2.52499e-06)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533521,0.00077253) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217518,-0.0196151) , 
6, 41.8354, 1, 0, 0.50143,-0.00380448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486869,0.00984749) , 
2, 100.26, 1, 0, 0.5,4.76329e-06)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232046,-0.0367306) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.581039,0.00528362) , 
1, 485.272, 1, 0, 0.464585,-0.026338) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545766,0.0102658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489449,-0.00255681) , 
4, 3.06974, 1, 0, 0.506465,0.0048101) , 
4, 3.03374, 1, 0, 0.5,2.07823e-06)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423883,-0.0168778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500932,0.000280596) , 
8, 0.299431, 1, 0, 0.495474,-0.00316567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558977,0.0112943) , 
4, 3.13484, 1, 0, 0.5,1.81807e-06)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0885649,-0.0190656) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564379,0.00696448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507304,-0.00340313) , 
3, 1094.94, 1, 0, 0.529771,0.00298079) , 
0, 89.3352, 1, 0, 0.5,2.71856e-06)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0690107,-0.0369671) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51955,0.000129478) , 
1, 398.021, 1, 0, 0.489407,-0.00440019) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643598,0.0218075) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497324,-0.00386746) , 
11, 607.1, 1, 0, 0.566673,0.0276964) , 
1, 640.641, 1, 0, 0.5,1.63168e-07)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587551,0.0086325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278249,-0.0131137) , 
0, 127.384, 1, 0, 0.498654,0.01291) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554618,0.00313888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34729,-0.0199905) , 
2, 47.0363, 1, 0, 0.500989,-0.00948995) , 
7, 0.449008, 1, 0, 0.5,-4.64777e-06)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423216,-0.0133384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.61603,0.00899412) , 
1, 577.038, 1, 0, 0.484393,-0.0204174) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556263,0.00764928) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473373,-0.00191117) , 
8, 2.39357, 1, 0, 0.504779,0.00624693) , 
2, 27.4535, 1, 0, 0.5,-3.43005e-06)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519974,-0.000107464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514834,0.0132111) , 
2, 100.26, 1, 0, 0.519469,0.00433327) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328569,-0.0225273) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418387,0.00238023) , 
4, 3.08774, 1, 0, 0.373467,-0.0281687) , 
5, 3.61234, 1, 0, 0.5,-7.78709e-07)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421976,-0.0232409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472896,0.000480266) , 
2, 34.3966, 1, 0, 0.462393,-0.0140481) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.637426,0.0122401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462068,-0.00253276) , 
6, 10.4422, 1, 0, 0.521727,0.00811559) , 
9, 0.14814, 1, 0, 0.5,-4.69767e-07)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524793,-0.00114066) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.694067,0.011434) , 
1, 620.817, 1, 0, 0.551703,0.00351621) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0204675,-0.0343674) , 
0, 151.199, 1, 0, 0.5,4.22516e-06)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596468,0.0193396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491954,-0.0040264) , 
11, 379.854, 1, 0, 0.521426,0.00926372) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422351,-0.0129092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554421,0.0113395) , 
7, 1.3465, 1, 0, 0.468891,-0.0134568) , 
10, 563.163, 1, 0, 0.5,-2.75926e-06)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445819,-0.00405932) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560217,0.012781) , 
4, 3.09433, 1, 0, 0.498654,0.0133179) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522492,0.000506466) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322055,-0.0332087) , 
8, 2.69275, 1, 0, 0.500989,-0.00977563) , 
7, 0.449008, 1, 0, 0.5,3.34285e-06)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530836,0.0166083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496813,-0.00193155) , 
3, 1005.93, 1, 0, 0.503332,0.00603573) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298867,-0.0415961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564072,0.00715617) , 
4, 3.12496, 1, 0, 0.489223,-0.0195013) , 
4, 3.11462, 1, 0, 0.5,4.74164e-06)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477379,0.00245722) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422819,-0.0125902) , 
7, 1.19623, 1, 0, 0.46102,-0.00708609) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575371,-0.000271456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634026,0.0259262) , 
8, 2.99141, 1, 0, 0.587312,0.0158881) , 
1, 569.897, 1, 0, 0.5,4.93318e-06)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4497,-0.00951761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.64931,0.0222705) , 
8, 0.312652, 1, 0, 0.55042,0.0257012) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243464,-0.011476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565546,0.00150985) , 
0, 108.37, 1, 0, 0.490962,-0.00459704) , 
8, 0.598593, 1, 0, 0.5,8.37285e-06)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465744,-0.0102509) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496333,0.0027106) , 
2, 34.0723, 1, 0, 0.487191,-0.00366662) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60082,0.00855225) , 
9, 0.888434, 1, 0, 0.5,7.56311e-06)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557977,0.0135429) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494737,-0.00587614) , 
10, 487.755, 1, 0, 0.521426,0.00855859) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422351,-0.012073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554421,0.0107265) , 
7, 1.3465, 1, 0, 0.468891,-0.0124048) , 
10, 563.163, 1, 0, 0.5,8.77168e-06)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388362,-0.00691328) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575884,0.0107131) , 
1, 483.735, 1, 0, 0.498654,0.0121915) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554618,0.00287666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34729,-0.0187778) , 
2, 47.0363, 1, 0, 0.500989,-0.00893304) , 
7, 0.449008, 1, 0, 0.5,1.21809e-05)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232046,-0.0341871) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.581039,0.00497171) , 
1, 485.272, 1, 0, 0.464585,-0.0236651) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545766,0.00976279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489449,-0.00251532) , 
4, 3.06974, 1, 0, 0.506465,0.00433458) , 
4, 3.03374, 1, 0, 0.5,1.25532e-05)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596468,0.0170358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491954,-0.00338043) , 
11, 379.854, 1, 0, 0.521426,0.008385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556487,0.0146539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438982,-0.00988937) , 
7, 0.149846, 1, 0, 0.468891,-0.0121465) , 
10, 563.163, 1, 0, 0.5,1.13242e-05)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460059,-0.0115334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46577,0.00610284) , 
2, 67.389, 1, 0, 0.462393,-0.0136288) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507973,-0.000539684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.606238,0.0186911) , 
7, 2.68609, 1, 0, 0.521727,0.00789799) , 
9, 0.14814, 1, 0, 0.5,1.51612e-05)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49373,0.00221677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498674,-0.00624422) , 
7, 1.19691, 1, 0, 0.495474,-0.00269778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558977,0.00986656) , 
4, 3.13484, 1, 0, 0.5,1.65565e-05)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477379,0.00224699) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422819,-0.0116828) , 
7, 1.19623, 1, 0, 0.46102,-0.00661598) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657806,0.0128419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486421,-0.00682615) , 
11, 555.764, 1, 0, 0.587312,0.0148708) , 
1, 569.897, 1, 0, 0.5,1.59462e-05)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465744,-0.00932483) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496333,0.00238921) , 
2, 34.0723, 1, 0, 0.487191,-0.00355009) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60082,0.00833876) , 
9, 0.888434, 1, 0, 0.5,1.80515e-05)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535495,-0.000807328) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587002,0.0177056) , 
7, 2.69179, 1, 0, 0.54686,0.0119115) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501127,0.00315147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395906,-0.0142801) , 
7, 0.449008, 1, 0, 0.466722,-0.00842862) , 
8, 2.24399, 1, 0, 0.5,1.79125e-05)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47497,6.15379e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418107,-0.019132) , 
4, 3.11466, 1, 0, 0.462393,-0.0137739) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.637426,0.0114614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462068,-0.00214635) , 
6, 10.4422, 1, 0, 0.521727,0.00798679) , 
9, 0.14814, 1, 0, 0.5,1.82812e-05)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0362194,-0.0419194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608397,0.00280452) , 
0, 87.7431, 1, 0, 0.570676,0.00446378) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0365953,-0.0362289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350301,0.00894553) , 
7, 2.0936, 1, 0, 0.144233,-0.022351) , 
0, 141.682, 1, 0, 0.5,1.96396e-05)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550077,0.0183724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463458,-0.00852341) , 
3, 1005.93, 1, 0, 0.481457,-0.0084123) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651355,0.0289612) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488835,-0.00413728) , 
4, 3.10344, 1, 0, 0.525099,0.011371) , 
4, 3.0944, 1, 0, 0.5,-6.63207e-06)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456114,0.00318096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293567,-0.0238017) , 
0, 122.647, 1, 0, 0.407216,-0.0125286) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608729,0.00540715) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.226409,-0.0219381) , 
6, 41.6868, 1, 0, 0.563424,0.00856694) , 
1, 499.154, 1, 0, 0.5,1.70459e-06)    );
   return;
};

// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
